/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductListing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'city' : IDL.Text,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'imageId' : IDL.Opt(IDL.Text),
  'pincode' : IDL.Text,
  'price' : IDL.Nat,
  'farmer' : IDL.Principal,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending_payment' : IDL.Null,
  'completed' : IDL.Null,
  'payment_confirmed' : IDL.Null,
  'in_delivery' : IDL.Null,
  'ready_for_pickup' : IDL.Null,
});
export const DeliveryType = IDL.Variant({
  'pickup' : IDL.Null,
  'delivery' : IDL.Null,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'listingId' : IDL.Nat,
  'deliveryType' : DeliveryType,
  'seller' : IDL.Principal,
  'upiRef' : IDL.Opt(IDL.Text),
  'totalAmount' : IDL.Nat,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'buyer' : IDL.Principal,
});
export const Role = IDL.Variant({ 'consumer' : IDL.Null, 'farmer' : IDL.Null });
export const UserProfile = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'role' : Role,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([IDL.Nat], [], []),
  'confirmPayment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createProductListing' : IDL.Func([ProductListing], [IDL.Nat], []),
  'deactivateListing' : IDL.Func([IDL.Nat], [], []),
  'deleteListing' : IDL.Func([IDL.Nat], [], []),
  'getAllActiveListings' : IDL.Func([], [IDL.Vec(ProductListing)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getBuyerOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(ProductListing)], ['query']),
  'getListingsByCity' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductListing)],
      ['query'],
    ),
  'getListingsByPincode' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ProductListing)],
      ['query'],
    ),
  'getListingsFromFarmDirect' : IDL.Func(
      [],
      [IDL.Vec(ProductListing)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
  'getSellerOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Nat, IDL.Nat, DeliveryType], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductListing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'city' : IDL.Text,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'imageId' : IDL.Opt(IDL.Text),
    'pincode' : IDL.Text,
    'price' : IDL.Nat,
    'farmer' : IDL.Principal,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending_payment' : IDL.Null,
    'completed' : IDL.Null,
    'payment_confirmed' : IDL.Null,
    'in_delivery' : IDL.Null,
    'ready_for_pickup' : IDL.Null,
  });
  const DeliveryType = IDL.Variant({
    'pickup' : IDL.Null,
    'delivery' : IDL.Null,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'listingId' : IDL.Nat,
    'deliveryType' : DeliveryType,
    'seller' : IDL.Principal,
    'upiRef' : IDL.Opt(IDL.Text),
    'totalAmount' : IDL.Nat,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'buyer' : IDL.Principal,
  });
  const Role = IDL.Variant({ 'consumer' : IDL.Null, 'farmer' : IDL.Null });
  const UserProfile = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'role' : Role,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([IDL.Nat], [], []),
    'confirmPayment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createProductListing' : IDL.Func([ProductListing], [IDL.Nat], []),
    'deactivateListing' : IDL.Func([IDL.Nat], [], []),
    'deleteListing' : IDL.Func([IDL.Nat], [], []),
    'getAllActiveListings' : IDL.Func([], [IDL.Vec(ProductListing)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getBuyerOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListing' : IDL.Func([IDL.Nat], [IDL.Opt(ProductListing)], ['query']),
    'getListingsByCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductListing)],
        ['query'],
      ),
    'getListingsByPincode' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ProductListing)],
        ['query'],
      ),
    'getListingsFromFarmDirect' : IDL.Func(
        [],
        [IDL.Vec(ProductListing)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
    'getSellerOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Nat, IDL.Nat, DeliveryType], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };