/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DeliveryType = { 'pickup' : null } |
  { 'delivery' : null };
export interface FounderStats {
  'totalOrders' : bigint,
  'pendingWithdrawal' : bigint,
  'totalFeesCollected' : bigint,
  'withdrawnAmount' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'platformFee' : bigint,
  'listingId' : bigint,
  'buyerLocationUpdatedAt' : [] | [Time],
  'deliveryType' : DeliveryType,
  'seller' : Principal,
  'sellerLat' : [] | [number],
  'sellerLng' : [] | [number],
  'upiRef' : [] | [string],
  'totalAmount' : bigint,
  'sellerAmount' : bigint,
  'timestamp' : Time,
  'quantity' : bigint,
  'sellerLocationUpdatedAt' : [] | [Time],
  'buyerLat' : [] | [number],
  'buyerLng' : [] | [number],
  'buyer' : Principal,
}
export interface OrderLocations {
  'buyerLocationUpdatedAt' : [] | [Time],
  'sellerLat' : [] | [number],
  'sellerLng' : [] | [number],
  'sellerLocationUpdatedAt' : [] | [Time],
  'buyerLat' : [] | [number],
  'buyerLng' : [] | [number],
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending_payment' : null } |
  { 'completed' : null } |
  { 'payment_confirmed' : null } |
  { 'in_delivery' : null } |
  { 'ready_for_pickup' : null };
export interface OrderWithFees {
  'order' : Order,
  'platformFee' : bigint,
  'sellerAmount' : bigint,
}
export interface ProductListing {
  'id' : bigint,
  'title' : string,
  'active' : boolean,
  'city' : string,
  'unit' : string,
  'description' : string,
  'quantity' : bigint,
  'imageId' : [] | [string],
  'pincode' : string,
  'price' : bigint,
  'farmer' : Principal,
}
export interface PublicUserProfile {
  'upiQrImageId' : [] | [string],
  'city' : string,
  'name' : string,
  'role' : Role,
  'upiId' : [] | [string],
  'phone' : string,
  'pincode' : string,
  'acceptsCashOnDelivery' : boolean,
}
export type Role = { 'consumer' : null } |
  { 'farmer' : null };
export type Time = bigint;
export interface UserProfile {
  'upiQrImageId' : [] | [string],
  'city' : string,
  'name' : string,
  'role' : Role,
  'upiId' : [] | [string],
  'phone' : string,
  'pincode' : string,
  'acceptsCashOnDelivery' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[bigint], undefined>,
  'confirmPayment' : ActorMethod<[bigint, string], undefined>,
  'createProductListing' : ActorMethod<[ProductListing], bigint>,
  'deactivateListing' : ActorMethod<[bigint], undefined>,
  'deleteListing' : ActorMethod<[bigint], undefined>,
  'getAllActiveListings' : ActorMethod<[], Array<ProductListing>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllOrdersWithFees' : ActorMethod<[], Array<OrderWithFees>>,
  'getBuyerOrders' : ActorMethod<[Principal], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFounderStats' : ActorMethod<[], FounderStats>,
  'getListing' : ActorMethod<[bigint], [] | [ProductListing]>,
  'getListingsByCity' : ActorMethod<[string], Array<ProductListing>>,
  'getListingsByPincode' : ActorMethod<[string], Array<ProductListing>>,
  'getListingsFromFarmDirect' : ActorMethod<[], Array<ProductListing>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrderLocations' : ActorMethod<[bigint], [] | [OrderLocations]>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getSellerOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserPublicProfile' : ActorMethod<[Principal], [] | [PublicUserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[bigint, bigint, DeliveryType], bigint>,
  'recordWithdrawal' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderLocation' : ActorMethod<[bigint, number, number], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];